#!/usr/bin/env bash

# Displays "Best school" 10 times using the until loop.

#On the 9th iteration, displays 'Hi' before "Best School".
count=0

While [ $count - It 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best school"
	(( count ++ ))
done




